[project]
name = "quasigeostrophic-flow"
version = "0.2.1"
description = "QG turbulence simulation with Hydra and WandB tracking"
authors = [
    {name = "Akhil Sadam", email = "sadam.akhil@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "lightning",
    "torch",
    "einops",
    "tqdm",
    "matplotlib",
    "ffmpeg-python",
    "wandb",
    "gitpython",
    "jpcm",
    "pyyaml",
    "pytest",
    "mura>=0.3.0",
    "netcdf4",
    "hydra-core",
    "omegaconf",
]

[options.packages.find]
where = "src"

[build-system]
requires = [
    "uv>=0.7.20",
    "setuptools",
]


[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
    "--capture=no",
    '-vvv'
    ]
